console.log(!!0);   // (출력값) false
console.log(!!1);   // (출력값) true
console.log(!!'string');   // (출력값) true
console.log(!!'');   // (출력값) false
console.log(!!null);   // (출력값) false
console.log(!!undefined);   // (출력값) false
console.log(!!{});   // (출력값) true
console.log(!!true);   // (출력값) true
console.log(!!false);   // (출력값) false
console.log(!![1,2,3]);   // (출력값) true
console.log(!![]);      // (출력값) true